### ISSUE TITLE
why is pushing from ec2 instance as user Ubuntu?

### ISSUE THREAD

**Issue by quinnliu** [Laybium/laybium_server#3]
<img width="316" alt="screen shot 2016-10-18 at 8 35 02 am" src="https://cloud.githubusercontent.com/assets/2585159/19466805/d87b1d0e-950d-11e6-928e-bb088aa681ce.png">

**Comment by quinnliu** [comment]
@vatteh doing this allowed me to push to the develop branch as myself in terminal before commit

```
$ GIT_COMMITTER_EMAIL=your_github_email@example.com
$ GIT_AUTHOR_EMAIL=your_github_email@example.com
```

[source](https://help.github.com/articles/setting-your-email-in-git/)

**Comment by vatteh** [comment]
Thanks Q! I'll give this a shot.
